# -*- coding: utf-8 -*-
"""kütüphane_yönetim_sistemi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1baVYK6GBsjuq85DyEN8uXCG8RWTM_OqV
"""

class Kitap():
  def __init__(self, kitap_id, ad, yazar):
    self.kitap_id = kitap_id
    self.ad = ad
    self.yazar = yazar
    self.durum = "mevcut"
  def durum_guncelle(self, yeni_durum):
    self.durum = yeni_durum

class Uye():
  def __init__(self, uye_id, ad):
    self.uye_id = uye_id
    self.ad = ad
    self.odunc_kitaplar =[]
  def kitap_ekle(self, kitap):
    self.odunc_kitaplar.append(kitap)
  def kitap_iade(self, kitap_id):
    self.odunc_kitaplar = [kitap for kitap in self.odunc_kitaplar if kitap.kitap_id != kitap_id]

class Odunc():
  def __init__(self, uye, kitap):
    self.uye = uye
    self.kitap = kitap
  def odunc_al(self):
    if self.kitap.durum == "mevcut":
       self.kitap.durum_guncelle("ödünçte")
       self.uye.kitap_ekle(self.kitap)
       print(f"{self.kitap.ad} ödünç alındı.")
    else:
      print("Kitap şu anda ödünçte.")
  def iade_et(self):
    self.kitap.durum_guncelle("mevcut")
    self.uye.kitap_iade(self.kitap.kitap_id)
    print(f"{self.kitap.ad} iade edildi.")

kitaplar = {} #kitap_id: Kitap Nesnesi
uyeler = {} #uye_id: Uye Nesnesi

def menu():
  print("\ Kütüphane Sistemi Menüsü")
  print("1. Kitap Ekle")
  print("2. üye Ekle")
  print("3. Kitap Ödünç Al")
  print("4. Kitap İade Et")
  print("5. Tüm Kitapları Gör")
  print("6. Çıkış")

while True:
  menu()
  secim = input("Seçiminiz: ")
  if secim == "1":
    kitap_id = input("Kitap ıd: ")
    ad = input("Kitap Adı: ")
    yazar = input("Yazar: ")
    kitaplar[kitap_id] = Kitap(kitap_id, ad, yazar)
    print("Kitap Eklendi.")

  elif secim == "2":
    uye_id = input("Üye ıd: ")
    ad = input("Üye Adı: ")
    uyeler[uye_id] = Uye(uye_id, ad)
    print("Üye Eklendi.")

  elif secim == "3":
    uye_id = input("Üye ıd: ")
    kitap_id = input("Kitap ıd: ")
    if uye_id in uyeler and kitap_id in kitaplar:
     odunc = Odunc(uyeler[uye_id], kitaplar[kitap_id])
     odunc.odunc_al()
    else:
      print("Üye veya kitap bulunamadı.")

  elif secim == "4":
    uye_id = input ("Üye ıd: ")
    kitap_id= input ("Kitap ıd: ")
    if uye_id in uyeler and kitap_id in kitaplar:
      odunc = Odunc(uyeler[uye_id], kitaplar[kitap_id])
      odunc.iade_et()
    else:
      print("Üye veya kitap bulunamadı.")

  elif secim == "5":
    for k in kitaplar.values():
      print(f"{k.kitap_id} - {k.ad} ({k.durum})")
  elif secim == "6":
    print("Sistemden çıkılıyor.")
    break
  else:
    print("Geçersiz seçim.")